import React, {memo, useContext, useEffect, useMemo, useState} from 'react';
import type {CustomRendererProps, TBlock} from 'react-native-render-html';
import {AttachmentContext} from '@components/AttachmentContext';
import {getButtonRole} from '@components/Button/utils';
import {isDeletedNode} from '@components/HTMLEngineProvider/htmlEngineUtils';
import PressableWithoutFocus from '@components/Pressable/PressableWithoutFocus';
import {ShowContextMenuContext, showContextMenuForReport} from '@components/ShowContextMenuContext';
import ThumbnailImage from '@components/ThumbnailImage';
import {useMemoizedLazyExpensifyIcons} from '@hooks/useLazyAsset';
import useLocalize from '@hooks/useLocalize';
import useOnyx from '@hooks/useOnyx';
import useTheme from '@hooks/useTheme';
import useThemeStyles from '@hooks/useThemeStyles';
import {getFileName, getFileType, splitExtensionFromFileName} from '@libs/fileDownload/FileUtils';
import Navigation from '@libs/Navigation/Navigation';
import {isArchivedNonExpenseReport} from '@libs/ReportUtils';
import tryResolveUrlFromApiRoot from '@libs/tryResolveUrlFromApiRoot';
import variables from '@styles/variables';
import CONST from '@src/CONST';
import ONYXKEYS from '@src/ONYXKEYS';
import ROUTES from '@src/ROUTES';

function ImageRenderer({tnode}: CustomRendererProps<TBlock>) {
    const icons = useMemoizedLazyExpensifyIcons(['Document', 'GalleryNotFound']);
    const styles = useThemeStyles();
    const {translate} = useLocalize();
    const {type} = useContext(AttachmentContext);

    // Re-render this component when account.shouldUseStagingServer changes
    useOnyx(ONYXKEYS.SHOULD_USE_STAGING_SERVER, {canBeMissing: true});

    const htmlAttribs = tnode.attributes;
    const isDeleted = isDeletedNode(tnode);

    // There are two kinds of images that need to be displayed:
    //
    //     - Chat Attachment images
    //
    //           Images uploaded by the user account via the app or email.
    //           These have a full-sized image `htmlAttribs[CONST.ATTACHMENT_SOURCE_ATTRIBUTE]`
    //           and a thumbnail `htmlAttribs.src`. Both of these URLs need to have
    //           an authToken added to them in order to control who
    //           can see the images.
    //
    //     - Non-Attachment Images
    //
    //           These could be hosted from anywhere (Expensify or another source)
    //           and are not protected by any kind of access control e.g. certain
    //           Concierge responder attachments are uploaded to S3 without any access
    //           control and thus require no authToken to verify access.
    //
    const attachmentSourceAttribute =
        htmlAttribs[CONST.ATTACHMENT_SOURCE_ATTRIBUTE] ?? (new RegExp(CONST.ATTACHMENT_OR_RECEIPT_LOCAL_URL, 'i').test(htmlAttribs.src) ? htmlAttribs.src : null);
    const isAttachmentOrReceipt = !!attachmentSourceAttribute;
    const attachmentID = htmlAttribs[CONST.ATTACHMENT_ID_ATTRIBUTE];

    // Files created/uploaded/hosted by App should resolve from API ROOT. Other URLs aren't modified
    const previewSource = tryResolveUrlFromApiRoot(htmlAttribs.src);
    // The backend always returns these thumbnails with a .jpg extension, even for .png images.
    // As a workaround, we remove the .1024.jpg or .320.jpg suffix only for .png images,
    // For other image formats, we retain the thumbnail as is to avoid unnecessary modifications.
    const processedPreviewSource = typeof previewSource === 'string' ? previewSource.replaceAll(/\.png\.(1024|320)\.jpg$/g, '.png') : previewSource;
    const source = tryResolveUrlFromApiRoot(isAttachmentOrReceipt ? attachmentSourceAttribute : htmlAttribs.src);

    const alt = htmlAttribs.alt;
    const imageWidth = (htmlAttribs['data-expensify-width'] && parseInt(htmlAttribs['data-expensify-width'], 10)) || undefined;
    const imageHeight = (htmlAttribs['data-expensify-height'] && parseInt(htmlAttribs['data-expensify-height'], 10)) || undefined;
    const imagePreviewModalDisabled = htmlAttribs['data-expensify-preview-modal-disabled'] === 'true';

    const isChatAttachmentThumbnail = type === CONST.ATTACHMENT_TYPE.REPORT && isAttachmentOrReceipt;
    const shouldTopAlignChatThumbnail = isChatAttachmentThumbnail && !!imageWidth && !!imageHeight && imageHeight > imageWidth * 3;
    const thumbnailStyle = isChatAttachmentThumbnail
        ? [
              styles.webViewStyles.tagStyles.img,
              {width: variables.reportPreviewMaxWidth, maxWidth: '100%', height: variables.reportActionImagesSingleImageHeight},
          ]
        : styles.webViewStyles.tagStyles.img;

    const previewSourceCandidates = useMemo(() => {
        if (!isChatAttachmentThumbnail || typeof processedPreviewSource !== 'string') {
            return [processedPreviewSource];
        }

        const preview1024 = processedPreviewSource.replace(/\.320\.jpg(?=($|\?))/i, '.1024.jpg');

        // Very tall images can look blurry when we stretch a small thumbnail (generated by the backend based on the longest side)
        // to a card-sized container. Prefer the original source for extreme aspect ratios (and fall back if it fails).
        const expectedPreviewWidthAt1024 = imageWidth && imageHeight ? (imageWidth / Math.max(imageWidth, imageHeight)) * 1024 : undefined;
        const shouldPreferOriginalForChatThumbnail =
            shouldTopAlignChatThumbnail &&
            typeof source === 'string' &&
            typeof expectedPreviewWidthAt1024 === 'number' &&
            expectedPreviewWidthAt1024 < variables.reportPreviewMaxWidth * 0.5;

        return [
            ...new Set(
                shouldPreferOriginalForChatThumbnail ? [source, preview1024, processedPreviewSource] : [preview1024, processedPreviewSource],
            ),
        ];
    }, [imageHeight, imageWidth, isChatAttachmentThumbnail, processedPreviewSource, shouldTopAlignChatThumbnail, source]);

    const previewSourceCandidatesKey = useMemo(() => previewSourceCandidates.map((value) => (typeof value === 'string' ? value : 'non-string')).join('|'), [previewSourceCandidates]);

    const [previewSourceCandidateIndex, setPreviewSourceCandidateIndex] = useState(0);

    useEffect(() => {
        setPreviewSourceCandidateIndex(0);
    }, [previewSourceCandidatesKey]);

    const previewSourceToRender = previewSourceCandidates[previewSourceCandidateIndex] ?? processedPreviewSource;

    const fileType = getFileType(attachmentSourceAttribute);
    const fallbackIcon = fileType === CONST.ATTACHMENT_FILE_TYPE.FILE ? icons.Document : icons.GalleryNotFound;
    const theme = useTheme();

    let fileName = htmlAttribs[CONST.ATTACHMENT_ORIGINAL_FILENAME_ATTRIBUTE] || getFileName(`${isAttachmentOrReceipt ? attachmentSourceAttribute : htmlAttribs.src}`);
    const fileInfo = splitExtensionFromFileName(fileName);
    if (!fileInfo.fileExtension) {
        fileName = `${fileInfo?.fileName || CONST.DEFAULT_IMAGE_FILE_NAME}.jpg`;
    }

    const thumbnailImageComponent = (
        <ThumbnailImage
            previewSourceURL={previewSourceToRender}
            style={thumbnailStyle}
            isAuthTokenRequired={isAttachmentOrReceipt}
            fallbackIcon={fallbackIcon}
            imageWidth={imageWidth}
            imageHeight={imageHeight}
            isDeleted={isDeleted}
            altText={alt}
            fallbackIconBackground={theme.highlightBG}
            fallbackIconColor={theme.border}
            shouldDynamicallyResize={!isChatAttachmentThumbnail}
            objectPosition={shouldTopAlignChatThumbnail ? CONST.IMAGE_OBJECT_POSITION.TOP : CONST.IMAGE_OBJECT_POSITION.INITIAL}
            onLoadFailure={() => {
                if (previewSourceCandidateIndex >= previewSourceCandidates.length - 1) {
                    return;
                }
                setPreviewSourceCandidateIndex((currentIndex) => Math.min(currentIndex + 1, previewSourceCandidates.length - 1));
            }}
        />
    );

    return imagePreviewModalDisabled ? (
        thumbnailImageComponent
    ) : (
        <ShowContextMenuContext.Consumer>
            {({onShowContextMenu, anchor, report, isReportArchived, action, checkIfContextMenuActive, isDisabled, shouldDisplayContextMenu}) => (
                <AttachmentContext.Consumer>
                    {({reportID, accountID, type}) => (
                        <PressableWithoutFocus
                            style={[styles.noOutline]}
                            onPress={() => {
                                if (!source || !type) {
                                    return;
                                }

                                const attachmentLink = tnode.parent?.attributes?.href;
                                const route = ROUTES.REPORT_ATTACHMENTS?.getRoute({
                                    attachmentID,
                                    reportID,
                                    type,
                                    source,
                                    accountID,
                                    isAuthTokenRequired: isAttachmentOrReceipt,
                                    originalFileName: fileName,
                                    attachmentLink,
                                });
                                Navigation.navigate(route);
                            }}
                            onLongPress={(event) => {
                                if (isDisabled || !shouldDisplayContextMenu) {
                                    return;
                                }
                                return onShowContextMenu(() =>
                                    showContextMenuForReport(event, anchor, report?.reportID, action, checkIfContextMenuActive, isArchivedNonExpenseReport(report, isReportArchived)),
                                );
                            }}
                            isNested
                            shouldUseHapticsOnLongPress
                            role={getButtonRole(true)}
                            accessibilityLabel={translate('accessibilityHints.viewAttachment')}
                            sentryLabel={CONST.SENTRY_LABEL.HTML_RENDERER.IMAGE}
                        >
                            {thumbnailImageComponent}
                        </PressableWithoutFocus>
                    )}
                </AttachmentContext.Consumer>
            )}
        </ShowContextMenuContext.Consumer>
    );
}

export default memo(ImageRenderer, (prevProps, nextProps) => prevProps.tnode.attributes === nextProps.tnode.attributes);
